[build]
  publish = "web"
  command = "node scripts/generate-web-config.js"

[[redirects]]
  from = "/inbox"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/integrations"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
